<script src="<?php echo RESOURCE_PATH . '/lib/bootstrap/js/jquery.min.js'; ?>"></script>
<script src="<?php echo RESOURCE_PATH . '/lib/bootstrap/js/bootstrap.min.js'; ?>"></script>
<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<script src="<?php echo RESOURCE_PATH . '/lib/bootstrap/js/ie10-viewport-bug-workaround.js'; ?>"></script>
<script src="<?php echo RESOURCE_PATH . '/lib/js/all.js'; ?>"></script>

