 <!-- Bootstrap core CSS -->
<link rel="stylesheet" href="<?php echo RESOURCE_PATH . '/lib/bootstrap/css/bootstrap.css'; ?>">
<link rel="stylesheet" href="<?php echo RESOURCE_PATH . '/lib/css/all.css'; ?>">
<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<link href="<?php echo RESOURCE_PATH . '/lib/bootstrap/css/ie10-viewport-bug-workaround.css'; ?>" rel="stylesheet">
<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
