<nav id="top" class="navbar col-xs-12 col-sm-12 col-md-12">
    <div class="container">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="navbar-header col-xs-2 col-sm-2 col-md-2">
                <div class="collapse navbar-collapse narbar-content col-xs-10 col-sm-10 col-md-10">
                    <ul class="nav navbar-nav">
                        <li class="navbar-btn navbar-default"><a href="#">首页</a></li>
                        <li class="navbar-btn navbar-default"><a href="#">文档</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</nav>